### ISSUE TITLE
Logos ezmesure bibcnrs

### ISSUE THREAD

**Issue by FRANCKSYLVIE** [ezpaarse-project/ezmesure#15]
![logo bibcnrs](https://user-images.githubusercontent.com/10154941/30215949-cf497cc2-94b1-11e7-9d08-5ee7d1335b55.png)

![logo ezmesure2](https://user-images.githubusercontent.com/10154941/30215945-cac4a172-94b1-11e7-89ce-54b7134ab53b.png)

![logo ezmesure bibcnrs 1](https://user-images.githubusercontent.com/10154941/30215898-ac9df3ce-94b1-11e7-8cfe-2fdeca767e4b.png)
![ezmesure report bibcnrs logo](https://user-images.githubusercontent.com/15651080/30240821-e19bdd68-9577-11e7-80d2-eacab9a1f690.png)
![ezmesure report bibcnrs logo - edited](https://user-images.githubusercontent.com/15651080/30240873-f38b8af4-9578-11e7-82d1-dadceb7d9dc6.png)

**Comment by fredericinist** [comment]
![ezmesure report bibcnrs logo](https://user-images.githubusercontent.com/15651080/30240787-211bbcc0-9577-11e7-9b98-962daeeaebfa.png)
