### ISSUE TITLE
encoding incorrectly handled on profile page

### ISSUE THREAD

**Issue by tporquet** [ezpaarse-project/ezmesure#5]
See screenshot
![capture du 2017-01-06 09-03-26](https://cloud.githubusercontent.com/assets/2981650/21711405/34d663ae-d3ef-11e6-97c2-6d3326df624e.png)

**Comment by nojhamster** [comment]
It seems that fields retrieved from Shibboleth have to be decoded. (cf BibApi https://github.com/BibCnrs/BibApi/blob/dfcdb466c324a5416ef2cb90f63e5f878812a329/lib/controller/ebsco/login.js#L51-L53)

**Comment by pseudom** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Caractères accentués ezMESURE](https://trello.com/c/9D03GbQn/244-caracteres-accentues-ezmesure)

**Comment by nojhamster** [comment]
Should be fixed by 4c8b2a1a29f3e693361ad5d57db5c29703e8ef0a. I still need to decode names that are already registered, and I'm probably going to add the possibility to refresh the data from Shibboleth.
