### ISSUE TITLE
Logos des partenaires

### ISSUE THREAD

**Issue by sfmax54** [ezpaarse-project/ezmesure#8]
![universite-claude-bernard-lyon-1-logo](https://cloud.githubusercontent.com/assets/5325656/25330085/a8f28800-28de-11e7-9a0d-ad86024ef1b5.png)
![insa rouen](https://cloud.githubusercontent.com/assets/5325656/25232163/bc84b35e-25da-11e7-9dcf-75ac42534abb.jpg)
![limoges](https://cloud.githubusercontent.com/assets/5325656/25232162/bc829812-25da-11e7-9a40-9cfa3013aa12.jpg)
![logotype biu mtp 2016 quadri](https://cloud.githubusercontent.com/assets/5325656/25232160/bc80f3cc-25da-11e7-94bc-35ea7555817c.png)
![logo_univevry_20120228143104](https://cloud.githubusercontent.com/assets/5325656/25232165/bc910f1e-25da-11e7-9325-aae59b2185f3.png)
![logo-univ-lorraine](https://cloud.githubusercontent.com/assets/5325656/25232164/bc86a5c4-25da-11e7-990e-2909eecee3b1.png)
![logo_ups_toulouse3](https://cloud.githubusercontent.com/assets/5325656/25232161/bc8141f6-25da-11e7-9162-8c82b32a9ff8.png)

![logo utc](https://cloud.githubusercontent.com/assets/5325656/25232166/bc990c64-25da-11e7-98c5-6cadd9b45b26.png)
![rennes2](https://cloud.githubusercontent.com/assets/5325656/25232170/bc9cbb16-25da-11e7-9945-25adea919e15.png)
![sciences po](https://cloud.githubusercontent.com/assets/5325656/25232167/bc9b913c-25da-11e7-8bbd-a104990e5da1.png)
![strasbourg](https://cloud.githubusercontent.com/assets/5325656/25232168/bc9be3a8-25da-11e7-89f8-4c1a8b8d6b3f.jpg)
![ufranchecomte](https://cloud.githubusercontent.com/assets/5325656/25232171/bcab2cbe-25da-11e7-9101-42172f83157d.jpg)
![umontpellier](https://cloud.githubusercontent.com/assets/5325656/25232175/bcb3b53c-25da-11e7-8cb5-66809d9b0a54.png)
![umontpellier3](https://cloud.githubusercontent.com/assets/5325656/25232172/bcae60aa-25da-11e7-84ec-fd9dc0b86977.png)
![unistra](https://cloud.githubusercontent.com/assets/5325656/25232173/bcb272a8-25da-11e7-8fca-a9e6fdd5711e.png)
![univ brest](https://cloud.githubusercontent.com/assets/5325656/25232177/bcb642fc-25da-11e7-8d14-205420131d80.png)
![univ grenoble](https://cloud.githubusercontent.com/assets/5325656/25232174/bcb32e96-25da-11e7-87a6-296391241f3a.png)
![univ orleans](https://cloud.githubusercontent.com/assets/5325656/25232178/bcc08032-25da-11e7-8140-0d40209ebc89.png)
![univ paris8](https://cloud.githubusercontent.com/assets/5325656/25232179/bcc4c6ce-25da-11e7-999e-3ccdaa09bc31.png)
![univ polynesie francaise](https://cloud.githubusercontent.com/assets/5325656/25232182/bccae5cc-25da-11e7-8808-64e7fe9968c5.png)
![univ reims](https://cloud.githubusercontent.com/assets/5325656/25232181/bcca7b1e-25da-11e7-99e7-f7a57479e072.png)
![upmc-logotype](https://cloud.githubusercontent.com/assets/5325656/25232180/bcc8b36a-25da-11e7-97e1-576c5e7acc10.gif)
![ur1](https://cloud.githubusercontent.com/assets/5325656/25232183/bccd2f80-25da-11e7-8373-2af6617d3d98.jpg)
![utbm quadri](https://cloud.githubusercontent.com/assets/5325656/25232184/bcd78bce-25da-11e7-9b6e-9b48b81b01b7.png)
![utc-site-logo](https://cloud.githubusercontent.com/assets/5325656/25232185/bcdbc8f6-25da-11e7-9446-3d7f4d4b45b6.png)

**Comment by tporquet** [comment]
![logo-sciencespo-grenoble](https://user-images.githubusercontent.com/2981650/28271866-18bfde36-6b0a-11e7-9072-517b84321f65.png)

**Comment by fredericinist** [comment]
add logo insa lyon

**Comment by fredericinist** [comment]
add logo univ-rennes1

**Comment by fredericinist** [comment]
add logo univ-valenciennes

**Comment by FRANCKSYLVIE** [comment]
Add logo Rennes1

**Comment by fredericinist** [comment]
add logo INSERM

**Comment by fredericinist** [comment]
add istex logos

**Comment by fredericinist** [comment]
add CNAM logo

**Comment by fredericinist** [comment]
![UDL-Lyon3_WEB](https://user-images.githubusercontent.com/15651080/55069683-e89cb500-5084-11e9-8d85-cf83a3a29c7b.jpg)
